/* Generated By:JavaCC: Do not edit this line. RustLexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RustLexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 14;
  /** RegularExpression Id. */
  int MUT = 15;
  /** RegularExpression Id. */
  int FN = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int NUMBER = 18;
  /** RegularExpression Id. */
  int PLUS = 19;
  /** RegularExpression Id. */
  int MINUS = 20;
  /** RegularExpression Id. */
  int STAR = 21;
  /** RegularExpression Id. */
  int SLASH = 22;
  /** RegularExpression Id. */
  int EQ = 23;
  /** RegularExpression Id. */
  int SEMI = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"U+000B\"",
    "\"U+000C\"",
    "\"U+000D\"",
    "\"U+200E\"",
    "\"U+200F\"",
    "\"U+0020\"",
    "\"U+2028\"",
    "\"U+2029\"",
    "\"U+0085\"",
    "\"let\"",
    "\"mut\"",
    "\"fn\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\";\"",
  };

}
